name: Publish to JSR

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # Required for JSR OIDC authentication

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build packages
        run: |
          echo "JSR publishes TypeScript source directly, skipping build step"

      - name: Publish to JSR
        run: |
          # Use standalone config for JSR that doesn't depend on workspace packages
          bunx jsr publish --config jsr-standalone.json