name: Publish to JSR

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # Required for JSR OIDC authentication

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build packages
        run: |
          # Build individual packages first
          cd servers/web-fetch && bun run build && cd ../..
          cd packages/core && bun run build && cd ../..
          cd packages/shared && bun run build && cd ../..
          
          # Build main project
          bun run build || npx tsc --build --force

      - name: Publish to JSR
        run: npx jsr publish